### ISSUE TITLE
jcha fails parsing large object sizes

### ISSUE THREAD

**Issue by piotrkrokowski** [trivago/jcha#2]
I had to replace `Integer.parseInt` with `Long.parseLong(bytes)` in `ClassHistogramEntry:37`.

**Comment by christian-esken** [comment]
Hello piotrkrokowski. Sorry for letting you wait on your comment. For an unknown reason I missed the notification.
Thanks for the info. It makes sense to apply your change. Care to open a Pull Request?

**Comment by christian-esken** [comment]
Fixed by https://github.com/trivago/jcha/pull/4 . Closing manually, as the PR did not auto-close it.
