### ISSUE TITLE
Reversed sorting of histograms?

### ISSUE THREAD

**Issue by piotrkrokowski** [trivago/jcha#3]
It seems that the order of histograms is reversed.
Whenever I provide 2 histograms and they are sorted base on modification date it seems that the newer one is treated as the first one.

Seems that `ClassHistogram:273` should be`int timestampDiff = Long.signum(getSnapshotTimeMillisFrom() - o.getSnapshotTimeMillisFrom());`

**Comment by christian-esken** [comment]
Hello piotrkrokowski. Sorry for letting you wait on your comment. For an unknown reason I missed the notification.
IIRC the sorting defines the comparison order for
`HistogramAverager.calculateDiff(ClassHistogram ch1, ClassHistogram ch2)`. Looking at that code it looks like the reasult may actually be unexpected or wrong. If bytes increases, the result may be negative. Is this what you observe?

**Comment by christian-esken** [comment]
Fixed by https://github.com/trivago/jcha/pull/4 . Closing manually, as the PR did not auto-close it.
